### PR TITLE
Fix scenario builder data loss when renaming area

### LINKED ISSUE #605: Loss of sc-builder data / assertion failure when renaming areas
### Description
In some cases, when renaming areas that are connected by a link, one of the following happens :

- In debug mode : assertion failure **src/libs/antares/study/scenario-builder/TSnumberData.cpp:556** 
```cpp
#ifndef NDEBUG
    if (pTSNumberRules.width)
    {
        assert(pTSNumberRules.width == pArea->links.size());
    }
#endif
```
- In release mode, `assert`s are not run. Instead, valgrind indicates invalid reads. The TS numbers are reset to `rand`.

### How to reproduce

1. Create an empty study
2. Create 2 areas, keep their default names "Area 1" and "Area 2"
3. Create a link between those 2 areas
4. Rename "Area 1" to "XX"
5. Rename "Area 2" to "AA"

### PR DESCRIPTION
**Pull request by flomnes**
Fixes #605

### CODE REVIEW

File: src/libs/antares/study/study.cpp [hunk 1]
```diff
@@ -1022,12 +1022,12 @@ bool Study::areaRename(Area* area, AreaName newName)
     // Updating all hydro allocation
     areas.each([&](Data::Area& areait) { areait.hydro.allocation.rename(oldid, newid); });
 
+    ScenarioBuilderUpdater updaterSB(*this);
```
Comment (flomnes) [inline src/libs/antares/study/study.cpp:1025]: The destructor is called later, in particular after `areas.fixOrientationForAllInterconnections` (l. 1044). That's when the sc-builder tmp data is loaded into memory.

File: src/libs/antares/study/scenario-builder/TSnumberData.cpp [hunk 2]
```diff
@@ -560,13 +560,23 @@ void ntcTSNumberData::saveToINIFile(const Study& study, Yuni::IO::File::Stream&
     for (const auto& i : pArea->links)
     {
         const Data::AreaLink* link = i.second;
+        /*
```
Comment (guilpier-code) [inline src/libs/antares/study/scenario-builder/TSnumberData.cpp:563]: As you know, this is a workaround. 
This added block may not belong here, because : 
- it tries to do a job that should have been done before in the execution,
- it makes the current task less clear than it should.

Isn't it possible to make that job (for instance) in the **AreaList::renameArea(...)** function ?
If it's not, we should consider a refactoring to make it possible, I think.

**Review by guilpier-code — CHANGES_REQUESTED** [review]

File: src/libs/antares/study/scenario-builder/TSnumberData.cpp (hunk 2 above)
Comment (flomnes) [reply src/libs/antares/study/scenario-builder/TSnumberData.cpp:563]: You're right. I think lines 569-572 are not mandatory, I just need to make sure that areas have already been renamed when saving the temporary file sc-builder data.


The order is the following when renaming an area :
1. Rename areas
2. Save the sc. builder data in a temporary file
3. Change data in memory
4. Load the sc. builder data from the temporary file

We should not use `i.first` (l. 579) there is no way map `Area::links` is up-to-date at step 1, since it is updated (and must be updated) at step 3.

**Review by guilpier-code — APPROVED** [review]
