### PR TITLE
Digest: ignore thermal, renewable clusters, binding constraints

### LINKED ISSUE #840: Segfault when exporting digest, new variable "profit by plant" suspected
v8.3.1, BP21 variant

### PR DESCRIPTION
**Pull request by flomnes**
Avoid out of bound indices.

### CODE REVIEW

File: src/solver/variable/storage/average.h [hunk 1]
```diff
@@ -142,8 +142,12 @@ struct Average : public NextT
...
     void buildDigest(SurveyResults& report, int digestLevel, int dataLevel) const
     {
-        if ((dataLevel & Category::area || dataLevel & Category::setOfAreas)
-            && digestLevel & Category::digestAllYears)
+        const bool isCluster = (VCardT::categoryFileLevel & Category::de)
+                               || (VCardT::categoryFileLevel & Category::de_res);
+        const bool isBindingConstraint = VCardT::categoryFileLevel & Category::bc;
+        const bool isDigest = digestLevel & Category::digestAllYears;
+        if ((dataLevel & Category::area || dataLevel & Category::setOfAreas) && isDigest
+            && !isCluster && !isBindingConstraint)
```
Comment (guilpier-code) [inline src/solver/variable/storage/average.h:150]: Suggestion : 
```C++
const bool isCluster = (VCardT::categoryFileLevel & Category::de)
                               || (VCardT::categoryFileLevel & Category::de_res);
const bool isBindingConstraint = VCardT::categoryFileLevel & Category::bc;

// Here we could add a comment on why we must avoid clusters and BCs
if (isCluster || isBindingConstraint)
    return;

const bool isDigest = digestLevel & Category::digestAllYears;
if ((dataLevel & Category::area || dataLevel & Category::setOfAreas) && isDigest)
{
    ...
}
```

Comment (flomnes) [reply src/solver/variable/storage/average.h:150]: We want to call `NextType::buildDigest`, so we can't just `return`

Comment (guilpier-code) [reply src/solver/variable/storage/average.h:150]: I see

**Review by guilpier-code — APPROVED** [review]
