### PR TITLE
Fix segfault, add skipped to enabled constraints

### LINKED ISSUE #1430: Segfault on 8.7.0-beta3
https://antares-web.rte-france.com/studies/b527675e-8597-433a-a5f9-e97086c88c87

GDB output 

```
corrupted size vs. prev_size

Thread 3 "antares-8.7-sol" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe0cd4700 (LWP 69576)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: Aucun fichier ou dossier de ce type.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff79ae859 in __GI_abort () at abort.c:79
#2  0x00007ffff7a1926e in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7b43298 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7a212fc in malloc_printerr (str=str@entry=0x7ffff7b4144d "corrupted size vs. prev_size") at malloc.c:5347
#4  0x00007ffff7a2196b in unlink_chunk (p=p@entry=0x7fffd3eee070, av=0x7fffdc000020) at malloc.c:1454
#5  0x00007ffff7a22e8b in _int_free (av=0x7fffdc000020, p=0x7fffd3ead050, have_lock=<optimized out>) at malloc.c:4342
#6  0x00007ffff7f4c10d in LU_LibererMemoireLU () from libsirius_solver.so
#7  0x00007ffff7f2cfe9 in SPX_LibererProbleme () from libsirius_solver.so
#8  0x000055555591abdc in OPT_AppelDuSimplexe (problemeHebdo=0x5557155b1de0, NumIntervalle=0, optimizationNumber=1, optPeriodStringGenerator=
    std::shared_ptr<class OptPeriodStringGenerator> (use count 2, weak count 0) = {...}) at /home/omnesflo/Antares_Simulator/src/solver/optimisation/opt_appel_solveur_lineaire.cpp:274
#9  0x0000555555911a93 in OPT_OptimisationLineaire (problemeHebdo=0x5557155b1de0, adqPatchParams=...) at /home/omnesflo/Antares_Simulator/src/solver/optimisation/opt_optimisation_lineaire.cpp:111
#10 0x00005555558f53e4 in OPT_PilotageOptimisationLineaire (problemeHebdo=0x5557155b1de0, adqPatchParams=...)
    at /home/omnesflo/Antares_Simulator/src/solver/optimisation/opt_pilotage_optimisation_lineaire.cpp:90
#11 0x00005555558f4d94 in OPT_OptimisationHebdomadaire (pProblemeHebdo=0x5557155b1de0, adqPatchParams=...) at /home/omnesflo/Antares_Simulator/src/solver/optimisation/opt_optimisation_hebdo.cpp:52
#12 0x00005555558fd423 in Antares::Solver::Optimization::DefaultWeeklyOptimization::solve (this=0x555715a5d330) at /home/omnesflo/Antares_Simulator/src/solver/optimisation/weekly_optimization.cpp:42
#13 0x00005555558abbad in Antares::Solver::Simulation::Economy::year (this=0x7fffffff7540, progression=..., state=..., numSpace=0, randomForYear=..., failedWeekList=empty std::__cxx11::list, 
    isFirstPerformedYearOfSimulation=true) at /home/omnesflo/Antares_Simulator/src/solver/simulation/economy.cpp:167
#14 0x00005555557c18c9 in Antares::Solver::Simulation::yearJob<Antares::Solver::Simulation::Economy>::onExecute (this=0x55555cb4c740)
    at /home/omnesflo/Antares_Simulator/src/solver/main/../simulation/solver.hxx:179
#15 0x0000555556d287dc in Yuni::Job::IJob::execute (this=0x55555cb4c740, t=0x5557175f8ea0) at /home/omnesflo/Antares_Simulator/src/ext/yuni/src/yuni/job/job.cpp:64
#16 0x0000555556d32a21 in Yuni::Private::QueueService::JobAccessor<Yuni::Job::IJob>::Execute<Yuni::Private::QueueService::QueueThread> (job=..., thread=0x5557175f8ea0)
    at /home/omnesflo/Antares_Simulator/src/ext/yuni/src/yuni/private/jobs/queue/../../../job/queue/../fwd.h:41
#17 0x0000555556d32860 in Yuni::Private::QueueService::QueueThread::onExecute (this=0x5557175f8ea0) at /home/omnesflo/Antares_Simulator/src/ext/yuni/src/yuni/private/jobs/queue/thread.cpp:34
#18 0x00005555555f379d in Yuni::Private::Thread::threadCallbackExecute (arg=0x5557175f8ea0) at /home/omnesflo/Antares_Simulator/src/ext/yuni/src/yuni/thread/thread.cpp:111
#19 0x00007ffff7ed4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#20 0x00007ffff7aab133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

Valgrind output
```
==61301== Use of uninitialised value of size 8
==61301==    at 0x48C4F87: LU_ChainageParLigneDeL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5F07: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301==    by 0x4A853B: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_pilotage_optimisation_lineaire.cpp:90)
==61301== 
==61301== Use of uninitialised value of size 8
==61301==    at 0x48C4FFF: LU_ChainageParLigneDeL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5F07: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301==    by 0x4A853B: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_pilotage_optimisation_lineaire.cpp:90)
==61301== 
==61301== Invalid write of size 4
==61301==    at 0x48C5019: LU_ChainageParLigneDeL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5F07: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301==    by 0x4A853B: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_pilotage_optimisation_lineaire.cpp:90)
==61301==  Address 0x1dcbfd94c is 0 bytes after a block of size 211,212 alloc'd
==61301==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==61301==    by 0x48C4EC9: LU_ChainageParLigneDeL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5F07: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301== 
==61301== Invalid write of size 8
==61301==    at 0x48C501D: LU_ChainageParLigneDeL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5F07: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301==    by 0x4A853B: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_pilotage_optimisation_lineaire.cpp:90)
==61301==  Address 0x1f05112d8 is 0 bytes after a block of size 422,424 alloc'd
==61301==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==61301==    by 0x48C4EE0: LU_ChainageParLigneDeL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5F07: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301== 
==61301== Invalid read of size 8
==61301==    at 0x48C5EA8: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301==    by 0x4A853B: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_pilotage_optimisation_lineaire.cpp:90)
==61301==    by 0x4A7EEB: OPT_OptimisationHebdomadaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_hebdo.cpp:52)
==61301==  Address 0x1f05112d8 is 0 bytes after a block of size 422,424 alloc'd
==61301==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==61301==    by 0x48C4EE0: LU_ChainageParLigneDeL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5F07: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301== 
==61301== Invalid read of size 4
==61301==    at 0x48C5EAE: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301==    by 0x4A853B: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_pilotage_optimisation_lineaire.cpp:90)
==61301==    by 0x4A7EEB: OPT_OptimisationHebdomadaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_hebdo.cpp:52)
==61301==  Address 0x1dcbfd94c is 0 bytes after a block of size 211,212 alloc'd
==61301==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==61301==    by 0x48C4EC9: LU_ChainageParLigneDeL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5F07: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301== 
==61301== Use of uninitialised value of size 8
==61301==    at 0x48C5176: LU_LuSolvTriangleL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5775: LU_LuSolv (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C63F5: LU_LuSolvLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B5521: SPX_ResolutionDeSysteme (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A233D: SPX_CalculerBBarreAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A1F64: SPX_CalculerBBarre (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC6B2: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301==    by 0x4A853B: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_pilotage_optimisation_lineaire.cpp:90)
==61301== 
==61301== Invalid read of size 8
==61301==    at 0x48C5EA8: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C79F2: LU_LuSolvTransposeeSecondMembreHyperCreux (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B57BE: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2A06: SPX_CalculerErBMoins1AvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A5AFF: SPX_DualCalculerNBarreR (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC1CF: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301==  Address 0x1f05112d8 is 0 bytes after a block of size 422,424 alloc'd
==61301==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==61301==    by 0x48C4EE0: LU_ChainageParLigneDeL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5F07: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301== 
==61301== Invalid read of size 4
==61301==    at 0x48C5EAE: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C79F2: LU_LuSolvTransposeeSecondMembreHyperCreux (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B57BE: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2A06: SPX_CalculerErBMoins1AvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A5AFF: SPX_DualCalculerNBarreR (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC1CF: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301==  Address 0x1dcbfd94c is 0 bytes after a block of size 211,212 alloc'd
==61301==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==61301==    by 0x48C4EC9: LU_ChainageParLigneDeL (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C5F07: LU_LuSolvTriangleLTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C60EA: LU_LuSolvTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48C642C: LU_LuSolvTransposeeLuUpdate (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B56F1: SPX_ResolutionDeSystemeTransposee (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48A2D3B: SPX_CalculerPiAvecBaseReduite (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48AC68F: SPX_DualSimplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B8B85: SPX_SimplexeCalculs (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x48B86F9: SPX_Simplexe (in /home/omnesflo/Téléchargements/libsirius_solver.so)
==61301==    by 0x4CDC30: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, int, int, std::shared_ptr<OptPeriodStringGenerator>) (opt_appel_solveur_lineaire.cpp:253)
==61301==    by 0x4C4BEA: OPT_OptimisationLineaire(PROBLEME_HEBDO*, Antares::Data::AdequacyPatch::AdqPatchParams&) (opt_optimisation_lineaire.cpp:111)
==61301== 
[2023-07-13 17:14:38][solver][infos]  Solver: Standard resolution failed
[2023-07-13 17:14:38][solver][infos]  Solver: Retry in safe mode
[2023-07-13 17:14:38][solver][infos]  solver: resetting
[2023-07-13 17:17:42][solver][infos]   system memory report: 4184 Mib / 31705 Mib,  13.196657% free
BUG dans LU_SupprimerTermesInutilesDansColonne  NbTerm 0  CNbTermMatriceActive 1
BUG dans LU_SupprimerTermesInutilesDansColonne  NbTerm 0  CNbTermMatriceActive 1
```

### PR DESCRIPTION
**Pull request by payetvin**
close #1430

### CODE REVIEW

File: src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp [hunk 1]
```diff
@@ -422,7 +422,7 @@ std::vector<std::shared_ptr<BindingConstraint>> BindingConstraintsRepository::en
         std::vector<std::shared_ptr<BindingConstraint>> out;
         std::copy_if(pList.begin(), pList.end(), std::back_inserter(out),
                      [](const auto &bc) {
-                         return bc->enabled();
+                         return bc->enabled() && !bc->skipped();
                      });
```
Comment (flomnes) [inline src/libs/antares/study/binding_constraint/BindingConstraintsRepository.cpp:426]: Why not use `BindingConstraintsRepository::eachEnabled` ?

**Review by flomnes — APPROVED** [review]
