### PR TITLE
Fix memory leaks

### LINKED ISSUE #645: memory leaks on end-to-end tests
**Description**
Running end to end tests (**tests src\tests\end-to-end\simple-study.cpp**)  run in debug, a clear message points memory leaks, at least on Windows.
 
**How to Reproduce**
Run end to end tests in debug mode

**Screenshots and additional files**
mem-leaks

**OS and version**
 - Debug mode
 - OS: Windows
 - Antares Simulator version: 8.2

### PR DESCRIPTION
**Pull request by flomnes**
- [Use `std::weak_ptr` to avoid cyclic dependencies](https://en.cppreference.com/w/cpp/memory/weak_ptr)

> Another use for std::weak_ptr is to break reference cycles formed by objects managed by [std::shared_ptr](https://en.cppreference.com/w/cpp/memory/shared_ptr). If such cycle is orphaned (i.e., there are no outside shared pointers into the cycle), the shared_ptr reference counts cannot reach zero and the memory is leaked. To prevent this, one of the pointers in the cycle [can be made weak](https://en.cppreference.com/w/cpp/memory/weak_ptr/%7Eweak_ptr#Example).

- Free `ValeursGenereesParPays[numSpace][i]->AleaCoutDeProductionParPalier`

Valgrind still detects leaks, those will be fixed later.
```
*** No errors detected
==180016== 
==180016== HEAP SUMMARY:
==180016==     in use at exit: 14,325,551 bytes in 1,484 blocks
==180016==   total heap usage: 415,668 allocs, 414,184 frees, 2,263,016,404 bytes allocated
==180016== 
==180016== 81,344 bytes in 1 blocks are possibly lost in loss record 133 of 168
==180016==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==180016==    by 0x48F71A9: LU_ChainageParColonneDeU (lu_reorganisation_chainages.c:244)
==180016==    by 0x48F312D: LU_FactorisationCalculs (lu_factorisation_calculs.c:458)
==180016==    by 0x48F1CC4: LU_Factorisation (lu_factorisation.c:155)
==180016==    by 0x48D4882: SPX_FactoriserLaBase (spx_factoriser_la_base.c:305)
==180016==    by 0x48DC05F: SPX_TestPassageBaseReduiteBaseComplete (spx_ordonner_contraintes_pour_la_base.c:125)
==180016==    by 0x48CEE86: SPX_DualSimplexe (spx_dual_simplexe.c:471)
==180016==    by 0x48E2EE1: SPX_SimplexeCalculs (spx_simplexe_calculs.c:303)
==180016==    by 0x48E2360: SPX_Simplexe (spx_simplexe.c:100)
==180016==    by 0x5F6525: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, unsigned int, int) (opt_appel_solveur_lineaire.cpp:263)
==180016==    by 0x5EF13A: OPT_OptimisationLineaire(PROBLEME_HEBDO*, unsigned int) (opt_optimisation_lineaire.cpp:97)
==180016==    by 0x5E3047: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, unsigned int) (opt_pilotage_optimisation_lineaire.cpp:90)
==180016== 
==180016== 145,152 bytes in 9 blocks are definitely lost in loss record 155 of 168
==180016==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==180016==    by 0x2AF335: __gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::allocate(unsigned long, void const*) (new_allocator.h:114)
==180016==    by 0x2A0FF5: std::allocator_traits<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::allocate(std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, unsigned long) (alloc_traits.h:444)
==180016==    by 0x28B7F1: std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_allocate(unsigned long) (stl_vector.h:343)
==180016==    by 0x5E40E3: std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_default_append(unsigned long) (vector.tcc:635)
==180016==    by 0x5E3F2E: std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::resize(unsigned long) (stl_vector.h:937)
==180016==    by 0x5E383C: optimisationAllocateProblem(PROBLEME_HEBDO*, int) (opt_alloc_probleme_a_optimiser.cpp:179)
==180016==    by 0x5E39EF: OPT_AllocDuProblemeAOptimiser(PROBLEME_HEBDO*) (opt_alloc_probleme_a_optimiser.cpp:197)
==180016==    by 0x5E2FCB: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, unsigned int) (opt_pilotage_optimisation_lineaire.cpp:67)
==180016==    by 0x5E2A2C: OPT_OptimisationHebdomadaire(PROBLEME_HEBDO*, unsigned int) (opt_optimisation_hebdo.cpp:52)
==180016==    by 0x5B82DD: Antares::Solver::Simulation::NoAdequacyPatchOptimization::solve(Antares::Solver::Variable::State&, int, unsigned int) (economy.cpp:109)
==180016==    by 0x5B8AD1: Antares::Solver::Simulation::Economy::year(Antares::Solver::Progression::Task&, Antares::Solver::Variable::State&, unsigned int, Antares::Solver::Simulation::yearRandomNumbers&, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >&, bool) (economy.cpp:224)
==180016== 
==180016== 1,735,796 (86,016 direct, 1,649,780 indirect) bytes in 8 blocks are definitely lost in loss record 167 of 168
==180016==    at 0x483BE63: operator new(unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==180016==    by 0x2AF335: __gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::allocate(unsigned long, void const*) (new_allocator.h:114)
==180016==    by 0x2A0FF5: std::allocator_traits<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::allocate(std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, unsigned long) (alloc_traits.h:444)
==180016==    by 0x28B7F1: std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_allocate(unsigned long) (stl_vector.h:343)
==180016==    by 0x5E40E3: std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_default_append(unsigned long) (vector.tcc:635)
==180016==    by 0x5E3F2E: std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::resize(unsigned long) (stl_vector.h:937)
==180016==    by 0x5E385B: optimisationAllocateProblem(PROBLEME_HEBDO*, int) (opt_alloc_probleme_a_optimiser.cpp:180)
==180016==    by 0x5E39EF: OPT_AllocDuProblemeAOptimiser(PROBLEME_HEBDO*) (opt_alloc_probleme_a_optimiser.cpp:197)
==180016==    by 0x5E2FCB: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, unsigned int) (opt_pilotage_optimisation_lineaire.cpp:67)
==180016==    by 0x5E2A2C: OPT_OptimisationHebdomadaire(PROBLEME_HEBDO*, unsigned int) (opt_optimisation_hebdo.cpp:52)
==180016==    by 0x5B82DD: Antares::Solver::Simulation::NoAdequacyPatchOptimization::solve(Antares::Solver::Variable::State&, int, unsigned int) (economy.cpp:109)
==180016==    by 0x5B8AD1: Antares::Solver::Simulation::Economy::year(Antares::Solver::Progression::Task&, Antares::Solver::Variable::State&, unsigned int, Antares::Solver::Simulation::yearRandomNumbers&, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >&, bool) (economy.cpp:224)
==180016== 
==180016== 12,349,904 (13,696 direct, 12,336,208 indirect) bytes in 8 blocks are definitely lost in loss record 168 of 168
==180016==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==180016==    by 0x48E229B: SPX_Simplexe (spx_simplexe.c:65)
==180016==    by 0x5F6525: OPT_AppelDuSimplexe(PROBLEME_HEBDO*, unsigned int, int) (opt_appel_solveur_lineaire.cpp:263)
==180016==    by 0x5EF13A: OPT_OptimisationLineaire(PROBLEME_HEBDO*, unsigned int) (opt_optimisation_lineaire.cpp:97)
==180016==    by 0x5E3047: OPT_PilotageOptimisationLineaire(PROBLEME_HEBDO*, unsigned int) (opt_pilotage_optimisation_lineaire.cpp:90)
==180016==    by 0x5E2A2C: OPT_OptimisationHebdomadaire(PROBLEME_HEBDO*, unsigned int) (opt_optimisation_hebdo.cpp:52)
==180016==    by 0x5B82DD: Antares::Solver::Simulation::NoAdequacyPatchOptimization::solve(Antares::Solver::Variable::State&, int, unsigned int) (economy.cpp:109)
==180016==    by 0x5B8AD1: Antares::Solver::Simulation::Economy::year(Antares::Solver::Progression::Task&, Antares::Solver::Variable::State&, unsigned int, Antares::Solver::Simulation::yearRandomNumbers&, std::__cxx11::list<unsigned int, std::allocator<unsigned int> >&, bool) (economy.cpp:224)
==180016==    by 0x31EB35: Antares::Solver::Simulation::yearJob<Antares::Solver::Simulation::Economy>::onExecute() (solver.hxx:189)
==180016==    by 0x16D03F3: Yuni::Job::IJob::execute(Yuni::Thread::IThread*) (job.cpp:64)
==180016==    by 0x16DA7FC: void Yuni::Private::QueueService::JobAccessor<Yuni::Job::IJob>::Execute<Yuni::Private::QueueService::QueueThread>(Yuni::Job::IJob&, Yuni::Private::QueueService::QueueThread*) (fwd.h:41)
==180016==    by 0x16DA63B: Yuni::Private::QueueService::QueueThread::onExecute() (thread.cpp:34)
==180016== 
==180016== LEAK SUMMARY:
==180016==    definitely lost: 244,864 bytes in 25 blocks
==180016==    indirectly lost: 13,985,988 bytes in 1,252 blocks
==180016==      possibly lost: 81,344 bytes in 1 blocks
==180016==    still reachable: 13,355 bytes in 206 blocks
==180016==         suppressed: 0 bytes in 0 blocks
==180016== Reachable blocks (those to which a pointer was found) are not shown.
==180016== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```

### CODE REVIEW

File: src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp [hunk 1]
```diff
@@ -252,6 +265,12 @@ void OPT_LiberationMemoireDuProblemeAOptimiser(PROBLEME_HEBDO* ProblemeHebdo)
 
         if (ProblemeAResoudre->ProblemesSpx)
         {
+            for (int NumIntervalle = 0; NumIntervalle < NbIntervalles; NumIntervalle++)
+            {
+                SPX_LibererProbleme(
+                  (PROBLEME_SPX*)ProblemeAResoudre->ProblemesSpx->ProblemeSpx[NumIntervalle]);
+            }
+
```
Comment (flomnes) [inline src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp]: Do not call if OR-Tools is used.

Comment (flomnes) [reply src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp]: done

File: src/tests/end-to-end/simple-study.cpp [hunk 2]
```diff
@@ -12,469 +12,466 @@
...
-
-{ 
-	/*Get value*/
-	typename Antares::Solver::Variable::Storage<VCard>::ResultsType* result = nullptr;
-	simulation->variables.retrieveResultsForArea<VCard>(&result, pArea);
-	BOOST_TEST(result->avgdata.hourly[0] == expectedHourlyValue,			tt::tolerance(0.001));
-	BOOST_TEST(result->avgdata.daily[0]  == expectedHourlyValue * 24,		tt::tolerance(0.001));
-	BOOST_TEST(result->avgdata.weekly[0] == expectedHourlyValue * 24 * 7,	tt::tolerance(0.001));
+void checkVariable(SimulationEcoPtr& simulation, Area* pArea, double expectedHourlyValue)
+
```
Comment (guilpier-code) [inline src/tests/end-to-end/simple-study.cpp]: Remove empty line 42

File: src/tests/end-to-end/simple-study.cpp [hunk 3]
```diff
@@ -12,469 +12,466 @@
...
 
-	Settings pSettings;
-	pSettings.tsGeneratorsOnly = false;
-	pSettings.noOutput = false;
+    return pStudy->parameters.getYearsWeightSum();
+}
 
-	//Launch simulation
-	Solver::Simulation::ISimulation< Solver::Simulation::Economy >* simulation = new Solver::Simulation::ISimulation< Solver::Simulation::Economy >(*pStudy, pSettings, nullptr);
+void cleanSimulation(Study& study)
```
Comment (guilpier-code) [inline src/tests/end-to-end/simple-study.cpp]: Function **cleanSimulation(Study& study)** clears tables used by simulation and clears the study as well.
So I guess function **cleanSimulation(Study& study)**'s name does not fit to what it actually does.
Therefore this function should be split into 2 parts.
Regarding the simulation clearing part (that is a de-allocation part), it normally should be done inside the simulation destructor, but I don't know if it's easily doable. Anyway, if it is, it should simplify the destroying code in the current source file, and probably in the **"solver"** code.
I think it would be an interesting manner to make Antares source code cleaner. We should create a ticket for that.

File: src/tests/end-to-end/simple-study.cpp [hunk 4]
```diff
@@ -12,469 +12,466 @@
...
+    // Allocate all arrays
+    SIM_AllocationTableaux();
 
-	pStudy = nullptr;
-	// removed any global reference
-	Data::Study::Current::Set(nullptr);
+    // Let's go
+    simulation->run();
+
+    return simulation;
```
Comment (guilpier-code) [inline src/tests/end-to-end/simple-study.cpp]: **runSimulation(Study::Ptr pStudy)** should not return the simulation.
As a matter of fact, I think that the study **and** then the simulation (the simulation needs the study at creation) should be created in the tests. Therefore, the **runSimulation** should not exist, at least in the form it does now.
It would make the tests grow a bit, but then we could think about a refactoring to shorten them.

File: src/tests/end-to-end/simple-study.cpp [hunk 5]
```diff
@@ -12,469 +12,466 @@
...
 }
 
-//Very simple test with one area and one load and one year
+// Very simple test with one area and one load and one year
 BOOST_AUTO_TEST_CASE(one_mc_year_one_ts)
 {
-	//Create study
-	Study::Ptr pStudy = std::make_shared<Study>(true); // for the solver
+    // Create study
+    auto pStudy = std::make_shared<Study>(true); // for the solver
```
Comment (guilpier-code) [inline src/tests/end-to-end/simple-study.cpp]: Here, the study is shared pointer.

- Why isn't it a unique pointer ? (I guess that if we have to pass it at the simulation creation, a shared pointer is better)
- As it is supposed to be destroyed automatically, why do we have to clear it in the **cleanSimulation(Study& study)** function, though the destruction of the simulation ? Something is too complicated here.

Note that the **Study**'s **clear()** method is called by the **Study**'s destructor, so it should be called automatically at the end of tests.

File: src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp [hunk 6]
```diff
@@ -176,8 +183,10 @@ static void optimisationAllocateProblem(PROBLEME_HEBDO* ProblemeHebdo, const int
       = (double*)MemAlloc(ProblemeAResoudre->NombreDeVariables * sizeof(double));
     ProblemeAResoudre->Colonne = (int*)MemAlloc(ProblemeAResoudre->NombreDeVariables * sizeof(int));
 
-    ProblemeAResoudre->NomDesVariables.resize(ProblemeAResoudre->NombreDeVariables);
-    ProblemeAResoudre->NomDesContraintes.resize(ProblemeAResoudre->NombreDeContraintes);
+    ProblemeAResoudre->NomDesVariables
```
Comment (guilpier-code) [inline src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp]: Why is **ProblemeAResoudre->NomDesVariables** changed from a `std::vector<std::string>` to a `std::vector<std::string>*`, which is more complicated and less safe ?

Same thing for **ProblemeAResoudre->NomDesContraintes**

**Review by guilpier-code — DISMISSED** [review]

File: src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp (hunk 6 above)
Comment (flomnes) [reply src/solver/optimisation/opt_alloc_probleme_a_optimiser.cpp]: Because C++ object aren't destroyed (as in `~Object()`) when the memory is managed through `malloc/free` as it is here. It would be if the containing class was managed through `new/delete`.

**Review by kathvargasr — APPROVED** [review]
