### PR TITLE
Fix matrix width for survey results

### LINKED ISSUE #751: Crash related to Profit by clusters
Study : ERAA_test_V1_red_100y-V8.3
Solver : v8.3.0-rc1

antares-solver fails to write results for area DE00, probably because of the newly-introduced output variable "Profit by plant".

Output in debug mode :
```
[Mon Jul  4 13:48:35 2022][solver][infos] Exporting results : DE00
[Mon Jul  4 13:48:35 2022][solver][debug]  :: survey writing `/home/omnesflo/Téléchargements/ERAA_test_V1_red_100y-V8.3/output/20220704-1345eco/economy/mc-ind/00004/areas/de00/values-hourly.txt`
[Mon Jul  4 13:48:35 2022][solver][debug]  :: survey writing `/home/omnesflo/Téléchargements/ERAA_test_V1_red_100y-V8.3/output/20220704-1345eco/economy/mc-ind/00004/areas/de00/values-annual.txt`
/home/omnesflo/Antares_Simulator/src/solver/main/../simulation/../variable/storage/intermediate.hxx:123: void Antares::Solver::Variable::IntermediateValues::internalExportAnnualValues(Antares::Solver::Variable::SurveyResults&, const A&, bool) const [with unsigned int Size = 8785; VCardT = Antares::Solver::Variable::Economy::VCardProfitByPlant; A = double*]: Assertion `report.data.columnIndex < report.maxVariables && "Column index out of bounds"' failed.
Abandon (core dumped)
```

### LINKED ISSUE #752: Survey results : allocated matrix may be too narrow
https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/2ee4e46012336d49e69199dd80021e467eaccffa/src/solver/variable/surveyresults/surveyresults.cpp#L565-L584

Narrow as in "width too small"

Note that 3 (l. 568) is the number of variables per cluster (NODU, NP COSTS, PRODUCTION). Adding a new variable leads to this matrix being too small.

Also, renewable clusters are not taken into account. For some studies containing many renewable clusters, the allocated matrix will be too small (width) as well.

This will also happen when binding constraints will be introduced into output variables.

### PR DESCRIPTION
**Pull request by flomnes**

### CODE REVIEW

File: src/solver/variable/surveyresults/surveyresults.cpp [hunk 1]
```diff
@@ -562,10 +562,24 @@ static inline void WriteIndexHeaderToFileDescriptor(int precisionLevel,
...
+// Production
+
 // TOFIX - MBO 02/06/2014 nombre de colonnes fonction du nombre de variables
 SurveyResults::SurveyResults(uint maxVars, const Data::Study& s, const String& o) :
  data(s, o),
- maxVariables(Math::Max<uint>(maxVars, 3 * s.runtime->maxThermalClustersForSingleArea)),
+ maxVariables(Math::Max<uint>(
+   maxVars,
+   nbVariablesPerDetailThermalCluster * s.runtime->maxThermalClustersForSingleArea,
+   nbVariablesPerDetailRenewableCluster * s.runtime->maxThermalClustersForSingleArea)),
```
Comment (flomnes) [inline src/solver/variable/surveyresults/surveyresults.cpp]: Change 3 -> 4 since a new variable was added (net profit by cluster)

File: src/libs/antares/study/runtime/runtime.h [hunk 2]
```diff
@@ -167,8 +167,11 @@ class StudyRuntimeInfos
     //! Override enable/disable TS generation per cluster
     bool thermalTSRefresh = false;
 
-    //! The maximum number of clusters for each area
-    uint maxThermalClustersForSingleArea;
+    //! The maximum number of thermal clusters for each area
+    size_t maxThermalClustersForSingleArea = 0;
+
+    //! The maximum number of renewable clusters for each area
+    size_t maxRenewableClustersForSingleArea = 0;
```
Comment (flomnes) [inline src/libs/antares/study/runtime/runtime.h:174]: Also take renewable clusters into account, they were ignored until now.

File: src/libs/antares/study/runtime/runtime.cpp [hunk 3]
```diff
@@ -602,23 +604,76 @@ bool StudyRuntimeInfos::loadFromStudy(Study& study)
...
+}
+
+void StudyRuntimeInfos::initializeMaxClusters(const Study& study)
+{
+    this->maxThermalClustersForSingleArea
+      = maxNumberOfClusters<CompareAreasByNumberOfClusters::thermal>(study);
+    this->maxRenewableClustersForSingleArea
+      = maxNumberOfClusters<CompareAreasByNumberOfClusters::renewable>(study);
+}
+
```
Comment (flomnes) [inline src/libs/antares/study/runtime/runtime.cpp]: All of this allows us to compute the max number of thermal/renewable clusters with as little code duplication as possible. Remove templates ?

File: src/solver/variable/surveyresults/surveyresults.cpp (hunk 1 above)
Comment (JasonMarechal25) [inline src/solver/variable/surveyresults/surveyresults.cpp]: I think there is copy paste error
```suggestion
   nbVariablesPerDetailRenewableCluster * s.runtime->maxRenewableClustersForSingleArea)),
```

**Review by JasonMarechal25 — APPROVED** [review]
