### PR TITLE
Save NTC timeseries even if all coefficients are zero

### LINKED ISSUE #592: It is not possible to have multiple zero NTC TS
**Description**
Create a link between two areas. Set all coefficients to 0 for the NTC. The matrix is resized to 0x0, thus the number of direct and indirect TS is not equal. The study crashes at runtime.

**How to Reproduce**
See above.

**Expected behavior**
All coefficients should be saved, even if they're all 0.

**OS and version**
 - OS: All
 - Antares Simulator version: 8.2

### PR DESCRIPTION
**Pull request by flomnes**

### CODE REVIEW

File: src/libs/antares/array/matrix.hxx [hunk 1]
```diff
@@ -1202,7 +1205,7 @@ void Matrix<T, ReadWriteT>::saveToBuffer(std::string& data,
         isDecimal = Static::Type::IsDecimal<ReadWriteType>::Yes,
     };
 
-    if (not print_dimensions and containsOnlyZero(predicate))
+    if ((not print_dimensions and containsOnlyZero(predicate)) && !saveEvenIfAllZero)
```
Comment (guilpier-code) [inline src/libs/antares/array/matrix.hxx]: I would put it that way : 
```suggestion
    if (not print_dimensions and (containsOnlyZero(predicate) and not saveEvenIfAllZero))
```
more clear to me

**Review by guilpier-code — CHANGES_REQUESTED** [review]

File: src/libs/antares/array/matrix.hxx (hunk 1 above)
Comment (flomnes) [reply src/libs/antares/array/matrix.hxx]: Operator `and` is associative _ie_ `(x and y) and z == x and (y and z)`, but I agree.

In such cases, you can suggest changes using this button 
image

**Review by guilpier-code — APPROVED** [review]
