### PR TITLE
fix hydro hot start with refresh span enabled

### LINKED ISSUE #190: error on hydro study with playlist use and stochastic TS refresh span
There is an error when launching a hydro study with playlist use and refresh span (see study [069 Hydro Reservoir Model -enhanced-02-custom.zip](https://github.com/AntaresSimulatorTeam/Antares_Simulator/files/6070000/069.Hydro.Reservoir.Model.-enhanced-02-custom.zip)) : 

image

This is seems to be cause by the use of playlist with stochastic TS refresh span : 

image

image

If refresh span is disabled or first MC year is activated there is no issue with the study.

### PR DESCRIPTION
**Pull request by jmkerloch**
closes #190

### CODE REVIEW

**Review by sgatto — APPROVED** [review]

File: src/solver/simulation/solver.hxx [hunk 1]
```diff
@@ -1581,8 +1582,8 @@ void ISimulation<Impl>::loopThroughYears(uint firstYear,
         qs.wait(Yuni::qseIdle);
         qs.stop();
 
-        // At this point, the first set of parallel year(s) was run
-        if (!pFirstSetParallelWasRun)
+        // At this point, the first set of parallel year(s) was run with at least one year performed
+        if (!pFirstSetParallelWasRun && yearPerformed)
```
Comment (guilpier-code) [inline src/solver/simulation/solver.hxx]: - Ok, **pFirstSetParallelWasRun** has a bad name, and it should be replaced by its opposite : isFirstParallelSet, more clear (not sure it can be done within the current PR).
- We should even have a variable **isFirstParallelSetWithAPerformedYear**
- At least, if we should rename **pFirstSetParallelWasRun** as **pFirstSetParallelWithAPerformedYearWasRun**

**Review by guilpier-code — CHANGES_REQUESTED** [review]

File: src/solver/simulation/solver.hxx (hunk 1 above)
Comment (guilpier-code) [reply src/solver/simulation/solver.hxx]: For now, not sure we need an extra variable **yearPerformed**, we can use what already exist

**Review by guilpier-code — APPROVED** [review]

File: src/solver/simulation/solver.h [hunk 2]
```diff
@@ -167,8 +167,8 @@ class ISimulation : public Impl
     HydroManagement pHydroManagement;
     //! Hydro hot start
     bool pHydroHotStart;
-    //! The first set of parallel year(s) was already run ?
-    bool pFirstSetParallelWasRun;
+    //! The first set of parallel year(s) with a performed year was already run ?
+    bool pFirstSetParallelWithAPerformedYearWasRun;
```
Comment (sgatto) [inline src/solver/simulation/solver.h:171]: I would correct the english
it is a paralleSet rather than a SetParallel
`pFirstParalleSetWithAPerformedYearWasRun;`

**Review by sgatto — COMMENTED** [review]
I propose to change (again) the name of the variable
