### PR TITLE
When excluding output variables, reset it_info

### LINKED ISSUE #328: Both old and new renewable output variables appear when using thematic trimming
**Description**
Both old and new renewable output variables appear when using thematic trimming.

**How to Reproduce**
- Add a renewable cluster
- Switch to "aggregated"
- Run the simulation

**Expected behavior**
No variables related to new RES should appear. They do.

**Screenshots and additional files**

**OS and version**
 - OS: Windows, Linux
 - Antares Simulator version: 8.1-rc1

### PR DESCRIPTION
**Pull request by flomnes**
Fix #328

### CODE REVIEW

File: src/libs/antares/study/variable-print-info.cpp [hunk 1]
```diff
@@ -172,12 +172,15 @@ void AllVariablesPrintInfo::prepareForSimulation(bool userSelection,
...
 
+    auto saved_it = it_info;
+    it_info = allVarsPrintInfo.begin();
     for (const auto& varname : excluded_vars)
     {
         const bool res = setPrintStatus(varname, false);
         if (not res)
             logs.info() << "Variable " << varname << " not found. Could not remove it";
     }
+    it_info = saved_it;
```
Comment (guilpier-code) [inline src/libs/antares/study/variable-print-info.cpp:183]: Rather use **resetInfoIterator()** function

**Review by guilpier-code — CHANGES_REQUESTED** [review]

**Review by guilpier-code — APPROVED** [review]
