### PR TITLE
Warn the user about disabled renewable clusters only when relevant

### LINKED ISSUE #381: Renewable cluster is not found when TS numbers are specified by the user.
**Description**
Renewable cluster is not found when TS numbers are specified by the user. A warning is displayed, no effect on the simulation.

**How to Reproduce**
Change renewable modelling to "clusters". Specify custom TS years. Change renewable modelling to "aggregated". Launch simulation.

**Expected behavior**
No warning should be displayed, since renewable clusters should be ignored when `rgModelling==aggregated`.

**Screenshots and additional files**
a64852b3-e080-4696-b220-39aca7901ae5

**OS and version**
 - OS: Windows
 - Antares Simulator version: 8.1

**Additional context**
None

### PR DESCRIPTION
**Pull request by flomnes**
Fixes #381

### CODE REVIEW

File: src/libs/antares/study/scenario-builder/rules.cpp [hunk 1]
```diff
@@ -162,7 +162,7 @@ void Rules::loadFromInstrs(Study& study,
         }
     }
 
-    if (kind_of_scenario == "r")
+    if (kind_of_scenario == "r" && study.parameters.renewableGeneration() == rgClusters)
```
Comment (guilpier-code) [inline src/libs/antares/study/scenario-builder/rules.cpp]: use **study.parameters.renewableGeneration.isClusters()** instead ?

**Review by guilpier-code — CHANGES_REQUESTED** [review]

File: src/libs/antares/study/scenario-builder/rules.cpp (hunk 1 above)
Comment (flomnes) [reply src/libs/antares/study/scenario-builder/rules.cpp]: done

Comment (guilpier-code) [reply src/libs/antares/study/scenario-builder/rules.cpp]: Maybe we could remove all occurences of **study.parameters.renewableGeneration() == rgClusters or rgAggregated** and replace them with **study.parameters.renewableGeneration.isClusters()** or **study.parameters.renewableGeneration.isAggregated()**, so that there would be no more reference to enum **RenewableGenerationModelling** in these files and possibly we could remove header inclusion from them

Comment (flomnes) [reply src/libs/antares/study/scenario-builder/rules.cpp]: Ok to be corrected after changes related to ts-numbers & unit tests

Comment (flomnes) [reply src/libs/antares/study/scenario-builder/rules.cpp]: About that, see #426

**Review by guilpier-code — APPROVED** [review]
