### PR TITLE
Normalize simulation mode Expansion, fix logs

### LINKED ISSUE #1761: Wrong simulation mode when using CLI option --expansion
## How to reproduce
Execute
```bash
antares-8.7-solver --expansion <study>
```
See logs
```
forcing the simulation mode Economy
```

## Open question
Is it just in the logs, or is it a real bug ?

## Developer notes
https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/10278e9b4221713c49b0ab7cf72eaaa03611034d/src/libs/antares/study/parameters.cpp#L172-L186

https://github.com/AntaresSimulatorTeam/Antares_Simulator/blob/10278e9b4221713c49b0ab7cf72eaaa03611034d/src/libs/antares/study/parameters.cpp#L1041-L1058

### PR DESCRIPTION
**Pull request by flomnes**
## Goal of this PR
The goal of this PR is to **normalize mode Expansion**. Until now, it was a sort of hack for [antares-xpansion](https://github.com/AntaresSimulatorTeam/antares-xpansion).

Simulation mode Expansion is Economy, but with a single optimization instead of 2 optimizations + thermal heuristic for Economy / Adequacy.

## Functional changes
- Do not force the export of MPS files in Xpansion mode. MPS files still be enabled through the "include-exportmps" parameter, as usual
- Allow the export of simulation results (mc-ind & mc-all) in Xpansion mode. As usual, can be enabled through settings year-by-year and `synthesis`, with suffix "exp" for the output directory (e.g **20231117-0931exp**)
- Fix logs, display "Expansion" instead of "Economy"

## Technical changes
- Allow `Parameters::mode = stdmExpansion` (renamed `SimulationMode::Expansion`)
- Use `enum class` ("scoped enum") instead of C-style `enum`. Remove `stdmMax`
- Remove `bool Parameters::expansion`
- Remove file `xpansion.h` and constant `STUDY_MODE_EXPANSION`
- Factorize two `switch..case`
```diff
switch (a) {
 case A:
+case B:
   someCode(); 
  break;
-case B:
-  someCode();
-  break;  
}
```

## TODO
Generates tests results for new studies in mode expansion
https://github.com/AntaresSimulatorTeam/Antares_Simulator_Tests_NR/pull/10

### CODE REVIEW

File: src/libs/antares/study/parameters.cpp [hunk 1]
```diff
@@ -177,8 +177,9 @@ const char* StudyModeToCString(StudyMode mode)
         return "Economy";
```
Comment (guilpier-code) [inline src/libs/antares/study/parameters.cpp:177]: A bit off topic, but for any purpose : is **StudyMode** well named ? Or wouldn't it be better to rename it into  **SimulationMode** : after all, we use this mode when we instantiate the simulation, and it's not used in the **Study** (from what I know)

File: src/solver/simulation/sim_calcul_economique.cpp [hunk 2]
```diff
@@ -83,7 +83,7 @@ void SIM_InitialisationProblemeHebdo(Data::Study& study,
 
     auto& parameters = study.parameters;
 
-    problem.Expansion = parameters.expansion;
+    problem.Expansion = (parameters.mode == Data::stdmExpansion);
```
Comment (guilpier-code) [inline src/solver/simulation/sim_calcul_economique.cpp]: `Data::stdmExpansion ` : **stdm** probably means **study mode**. 
`Data::SimExpansion ` would be better.

File: src/ui/simulator/windows/inspector/constants.cpp [hunk 3]
```diff
@@ -269,9 +268,7 @@ const wxChar* const calendarWeeks[] = {wxT("MON  -  SUN"),
 
 const wxChar* const studyMode[] = {wxT("Economy"),
```
Comment (guilpier-code) [inline src/ui/simulator/windows/inspector/constants.cpp]: As already pointed : **studyMode** --> **simulationMode**

**Review by guilpier-code — CHANGES_REQUESTED** [review]

**Comment by JasonMarechal25** [comment]
Just a note.
In xpansion we use both "expansion" and "economy" mode. 

If user set xpansion mode "accurate" we use "expansion" in simulator, else "economy"

File: src/libs/antares/study/parameters.cpp (hunk 1 above)
Comment (flomnes) [reply src/libs/antares/study/parameters.cpp:177]: Done ! See https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1771/commits/f63d6c7c37bd07c22f8c04559c7eebfd8cc12d79

File: src/solver/simulation/sim_calcul_economique.cpp (hunk 2 above)
Comment (flomnes) [reply src/solver/simulation/sim_calcul_economique.cpp]: Done ! See https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1771/commits/f63d6c7c37bd07c22f8c04559c7eebfd8cc12d79

File: src/ui/simulator/windows/inspector/constants.cpp (hunk 3 above)
Comment (flomnes) [reply src/ui/simulator/windows/inspector/constants.cpp]: Done ! See https://github.com/AntaresSimulatorTeam/Antares_Simulator/pull/1771/commits/f63d6c7c37bd07c22f8c04559c7eebfd8cc12d79

File: src/libs/antares/study/fwd.h [hunk 4]
```diff
@@ -97,21 +97,19 @@ enum StudyError
...
 {
-    stdmUnknown = -1,
     //! Economic
-    stdmEconomy,
+    Economy,
     //! Adequacy (subset of the economy mode)
-    stdmAdequacy,
+    Adequacy,
     //! Expansion
-    stdmExpansion,
```
Comment (sylvlecl) [inline src/libs/antares/study/fwd.h:110]: Not necessarily for that PR, but should we rename it something more generic, like "ProblemsGeneration" ? I don't know enough the specifics of this mode to find an appropriate name though.

File: src/solver/optimisation/opt_optimisation_lineaire.cpp [hunk 5]
```diff
@@ -110,8 +110,7 @@ bool runWeeklyOptimization(const OptimizationOptions& options,
                                  writer))
             return false;
 
-        if (problemeHebdo->ExportMPS != Data::mpsExportStatus::NO_EXPORT
-            || problemeHebdo->Expansion)
+        if (problemeHebdo->ExportMPS != Data::mpsExportStatus::NO_EXPORT)
```
Comment (payetvin) [inline src/solver/optimisation/opt_optimisation_lineaire.cpp:113]: SimulationMode shouldn't be checked also ?

File: src/solver/simulation/sim_calcul_economique.cpp [hunk 6]
```diff
@@ -83,7 +83,7 @@ void SIM_InitialisationProblemeHebdo(Data::Study& study,
 
     auto& parameters = study.parameters;
 
-    problem.Expansion = parameters.expansion;
+    problem.Expansion = (parameters.mode == Data::SimulationMode::Expansion);
```
Comment (payetvin) [inline src/solver/simulation/sim_calcul_economique.cpp:86]: remove, only used here

**Review by guilpier-code — APPROVED** [review]

File: src/solver/optimisation/opt_optimisation_lineaire.cpp (hunk 5 above)
Comment (flomnes) [reply src/solver/optimisation/opt_optimisation_lineaire.cpp:113]: No, this is the goal of this PR. To de-correlate the MPS export & the simulation mode

File: src/libs/antares/study/fwd.h (hunk 4 above)
Comment (flomnes) [reply src/libs/antares/study/fwd.h:110]: Yes, this may be renamed
