### PR TITLE
Fix double free on ThermalCluster when in must-run

### LINKED ISSUE #306: Segfault when cleaning study
Branch feature/renewable

Start study `001\ One\ node\ -\ passive/`.

Segfault with backtrace

```
 (gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7969859 in __GI_abort () at abort.c:79
#2  0x00007ffff79d43ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7afe285 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff79dc47c in malloc_printerr (str=str@entry=0x7ffff7b00690 "double free or corruption (!prev)")
    at malloc.c:5347
#4  0x00007ffff79de12c in _int_free (av=0x7ffff7b2fb80 <main_arena>, p=0x555557f2b880, have_lock=<optimized out>)
    at malloc.c:4317
#5  0x000055555644a1e2 in __gnu_cxx::new_allocator<double>::deallocate (this=0x555557f29fa0, __p=0x555557f2b890)
    at /usr/include/c++/9/ext/new_allocator.h:128
#6  0x000055555644a11a in std::allocator_traits<std::allocator<double> >::deallocate (__a=..., 
    __p=0x555557f2b890, __n=8760) at /usr/include/c++/9/bits/alloc_traits.h:470
#7  0x0000555556449f94 in std::_Vector_base<double, std::allocator<double> >::_M_deallocate (
    this=0x555557f29fa0, __p=0x555557f2b890, __n=8760) at /usr/include/c++/9/bits/stl_vector.h:351
#8  0x0000555556449c3e in std::_Vector_base<double, std::allocator<double> >::~_Vector_base (
    this=0x555557f29fa0, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_vector.h:332
#9  0x00005555564499c5 in std::vector<double, std::allocator<double> >::~vector (this=0x555557f29fa0, 
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_vector.h:680
#10 0x0000555556560e13 in Antares::Data::ThermalCluster::~ThermalCluster (this=0x555557f29d10, 
    __in_chrg=<optimized out>)
    at /home/omnesflo/Antares_Simulator/src/libs/antares/study/parts/thermal/cluster.cpp:157
#11 0x000055555655f5da in std::_Sp_counted_ptr<Antares::Data::ThermalCluster*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x555557e064f0) at /usr/include/c++/9/bits/shared_ptr_base.h:377
#12 0x00005555563dbf3e in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555557e064f0)
    at /usr/include/c++/9/bits/shared_ptr_base.h:155
#13 0x00005555563dbd0d in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x555557f2b7f0, 
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:730
#14 0x00005555563dbb10 in std::__shared_ptr<Antares::Data::ThermalCluster, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x555557f2b7e8, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1169
#15 0x00005555563dbb5a in std::shared_ptr<Antares::Data::ThermalCluster>::~shared_ptr (this=0x555557f2b7e8, 
    __in_chrg=<optimized out>) at /usr/include/c++/9/bits/shared_ptr.h:103
#16 0x000055555655ef1e in std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> >::~pair (this=0x555557f2b760, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_pair.h:208
#17 0x000055555655ef4e in __gnu_cxx::new_allocator<std::_Rb_tree_node<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > > >::destroy<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > > (this=0x555557e10730, __p=0x555557f2b760)
    at /usr/include/c++/9/ext/new_allocator.h:153
#18 0x000055555655ebdf in std::allocator_traits<std::allocator<std::_Rb_tree_node<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > > > >::destroy<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > > (__a=..., __p=0x555557f2b760)
    at /usr/include/c++/9/bits/alloc_traits.h:497
#19 0x000055555655e125 in std::_Rb_tree<Yuni::CString<128u, false>, std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> >, std::_Select1st<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > >, std::less<Yuni::CString<128u, false> >, std::allocator<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > > >::_M_destroy_node (
    this=0x555557e10730, __p=0x555557f2b740) at /usr/include/c++/9/bits/stl_tree.h:642
#20 0x000055555655ce35 in std::_Rb_tree<Yuni::CString<128u, false>, std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> >, std::_Select1st<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > >, std::less<Yuni::CString<128u, false> >, std::allocator<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > > >::_M_drop_node (
    this=0x555557e10730, __p=0x555557f2b740) at /usr/include/c++/9/bits/stl_tree.h:650
#21 0x000055555655c0ae in std::_Rb_tree<Yuni::CString<128u, false>, std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> >, std::_Select1st<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > >, std::less<Yuni::CString<128u, false> >, std::allocator<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > > >::_M_erase (
    this=0x555557e10730, __x=0x555557f2b740) at /usr/include/c++/9/bits/stl_tree.h:1915
#22 0x000055555655b3ce in std::_Rb_tree<Yuni::CString<128u, false>, std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> >, std::_Select1st<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > >, std::less<Yuni::CString<128u, false> >, std::allocator<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > > >::~_Rb_tree (
    this=0x555557e10730, __in_chrg=<optimized out>) at /usr/include/c++/9/bits/stl_tree.h:995
#23 0x000055555655a950 in std::map<Yuni::CString<128u, false>, std::shared_ptr<Antares::Data::ThermalCluster>, std::less<Yuni::CString<128u, false> >, std::allocator<std::pair<Yuni::CString<128u, false> const, std::shared_ptr<Antares::Data::ThermalCluster> > > >::~map (this=0x555557e10730, __in_chrg=<optimized out>)
    at /usr/include/c++/9/bits/stl_map.h:300
#24 0x0000555556563e76 in Antares::Data::ThermalClusterList::~ThermalClusterList (this=0x555557e106d8, 
    __in_chrg=<optimized out>)
    at /home/omnesflo/Antares_Simulator/src/libs/antares/study/parts/thermal/cluster_list.cpp:27
#25 0x000055555655f81b in Antares::Data::PartThermal::~PartThermal (this=0x555557e106c8, 
    __in_chrg=<optimized out>)
    at /home/omnesflo/Antares_Simulator/src/libs/antares/study/parts/thermal/container.cpp:71
#26 0x00005555564db5bb in Antares::Data::Area::~Area (this=0x555557e103d0, __in_chrg=<optimized out>)
    at /home/omnesflo/Antares_Simulator/src/libs/antares/study/area/area.cpp:110
#27 0x00005555564ecd87 in Antares::Data::AreaList::clear (this=0x7ffff7108b18)
    at /home/omnesflo/Antares_Simulator/src/libs/antares/study/area/list.cpp:415
#28 0x0000555556498dfc in Antares::Data::Study::clear (this=0x7ffff6e66010)
    at /home/omnesflo/Antares_Simulator/src/libs/antares/study/study.cpp:137
#29 0x00005555561ac763 in SolverApplication::~SolverApplication (this=0x555557df7dc0, __in_chrg=<optimized out>)
    at /home/omnesflo/Antares_Simulator/src/solver/main.cpp:535
#30 0x00005555561ac82a in SolverApplication::~SolverApplication (this=0x555557df7dc0, __in_chrg=<optimized out>)
    at /home/omnesflo/Antares_Simulator/src/solver/main.cpp:544
#31 0x00005555561aca21 in main (argc=2, argv=0x7fffffffddd8)
    at /home/omnesflo/Antares_Simulator/src/solver/main.cpp:593
```

### PR DESCRIPTION
**Pull request by flomnes**

### CODE REVIEW

File: src/libs/antares/study/parts/thermal/container.cpp [hunk 1]
```diff
@@ -118,7 +118,7 @@ uint PartThermal::prepareClustersInMustRunMode()
             if ((i->second)->mustrun)
             {
                 // Detaching the thermal cluster from the main list...
-                ThermalCluster* cluster = list.detach(i);
+                std::shared_ptr<ThermalCluster> cluster = list.detach(i);
```
Comment (guilpier-code) [inline src/libs/antares/study/parts/thermal/container.cpp:121]: Here is what I missed : 
if you detach a (must-run) cluster from **list** to add it to **mustrunList**, then the cluster is no longer in **list**, but now in **mustrunList**.
So before this fix, destroying both lists should not cause a seg fault, as a cluster is either in a list ot the other.
How can it be destroyed twice ?

Comment (flomnes) [reply src/libs/antares/study/parts/thermal/container.cpp:121]: Here is what happened previously :
1. A `shared_ptr` was created pointing to an object of type `ThermalCluster`, in container `list`.
2. For must-run clusters, this `shared_ptr` was detached from list and added to `musttunList`. For that, we use the `detach` method as above.
3. Formerly, this method returned a raw pointer to the `ThermalCluster` object, and called the destructor of `std::pair<String, std::shared_ptr<ThermalCluster>>`, which called the destructor for each member of the pair, which called the destructor for `ThermalCluster`.
4. `mustrunList` contained a `shared_ptr<ThermalCluster>` that pointed to freed memory. Since the destructor for `ThermalCluster` does nothing, that memory address still contained a valid object. Thus the simulation could take place. However, using deallocated memory is undefined behavior and may lead to segfaults.
5. The segfault actually happened at the destruction of `mustrunList`, after the simulation and writing of outputs.

The proposed solution is to avoid exposing raw pointers (step 3 above). By doing so, the destructor of `ThermalCluster` is called only once at the end of the simulation.

image
