### PR TITLE
[FIX] Cleaned day ahead reserve management

### LINKED ISSUE #997: enum DayAheadReserveManagement, struct reserveManagement, etc. unused
See parameters.h / parameters.cpp

```
ag --nocolor --literal --line-number --smart-case --nogroup --column --stats -- reserveManagement .
ui/simulator/windows/options/advanced/advanced.h:134:31:    Component::Button* pBtnDARreserveManagement;
ui/simulator/windows/options/advanced/advanced.cpp:246:16:        pBtnDARreserveManagement = button;
ui/simulator/windows/options/advanced/advanced.cpp:368:20:        parameters.reserveManagement.daMode = Data::daGlobal;
ui/simulator/windows/options/advanced/advanced.cpp:442:63:      DayAheadReserveManagementModeToCString(study.parameters.reserveManagement.daMode));
ui/simulator/windows/options/advanced/advanced.cpp:444:12:    pBtnDARreserveManagement->caption(wxT("global"));
ui/simulator/windows/options/advanced/advanced.cpp:1049:26:    if (study.parameters.reserveManagement.daMode != Data::daGlobal)
ui/simulator/windows/options/advanced/advanced.cpp:1051:26:        study.parameters.reserveManagement.daMode = Data::daGlobal;
ui/simulator/windows/options/advanced/advanced.cpp:1063:26:    if (study.parameters.reserveManagement.daMode != Data::daLocal)
ui/simulator/windows/options/advanced/advanced.cpp:1065:26:        study.parameters.reserveManagement.daMode = Data::daLocal;
libs/antares/study/parameters.h:491:7:    } reserveManagement;
libs/antares/study/parameters.cpp:325:5:    reserveManagement.daMode = daGlobal;
libs/antares/study/parameters.cpp:690:15:            d.reserveManagement.daMode = daReserve;
libs/antares/study/parameters.cpp:695:11:        d.reserveManagement.daMode = daGlobal;
libs/antares/study/parameters.cpp:1780:61:                     DayAheadReserveManagementModeToCString(reserveManagement.daMode));
```
This struct/enum is only used in the GUI. It has no effect on the simulation. Consider some cleanup.

### PR DESCRIPTION
**Pull request by payetvin**
close #997

### CODE REVIEW

File: src/libs/antares/study/parameters.cpp [hunk 1]
```diff
@@ -587,8 +585,6 @@ static bool SGDIntLoadFamily_Optimization(Parameters& d,
         return value.to<bool>(d.include.thermal.minStablePower);
     if (key == "include-tc-min-ud-time")
         return value.to<bool>(d.include.thermal.minUPTime);
-    if (key == "include-dayahead")
-        return value.to<bool>(d.include.reserve.dayAhead);
```
Comment (flomnes) [inline src/libs/antares/study/parameters.cpp]: Keep this variable, it is used in **src/libs/antares/study/area/list.cpp:847**

**Review by flomnes — CHANGES_REQUESTED** [review]
You removed a variable that is used: `include.reserve.dayAhead`

**Review by flomnes — APPROVED** [review]
